chess/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SimpleChess.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

	url(r'^$', "chess.simpleChess.views.chess", name='chess'),
	url(r'^getGameFen/', "chess.simpleChess.views.getGameFen", name='getFen'),
    url(r'^admin/', include(admin.site.urls)),
)

chess/simpleChess/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.
class ChessGame(models.Model):
	fen = models.CharField(max_length=100)
	pgn = models.CharField(max_length=600)

class ChessForm(ModelForm):
	class Meta:
		model = ChessGame
		fenField = ['fen']
		pgnField = ['pgn']

chess/simpleChess/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader

from chess.simpleChess.models import ChessGame, ChessForm

# Create your views here.
def chess(request):

	if (request.method == 'POST'):
		game = ChessGame.objects.all()[0]
		f = ChessForm(request.POST, instance=game)
		f.save()
	else:
		if(len(ChessGame.objects.all()) > 0 ):
			game = ChessGame.objects.all()[0];
		else:
			game = ChessGame()
			game.fen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR"
			game.pgn = "new"
			game.save()
	f = ChessForm()
	return render(request, 'chess.html', {'gameData' : game, 'f' : f})


def getGameFen(request):
	if(len(ChessGame.objects.all()) > 0):
	    game = ChessGame.objects.all()[0]
	    pgnString = game.pgn
	    return HttpResponse(pgnString);
	else:
		return HttpResponse("No game found.");

chess/simpleChess/templates/chess.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Sjakk</title>

  <link rel="stylesheet" href="{% static "css/chessboard.css" %}" />
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
</head>
<body>

<style type="text/css">
.highlight-white {
  -webkit-box-shadow: inset 0 0 3px 3px yellow;
  -moz-box-shadow: inset 0 0 3px 3px yellow;
  box-shadow: inset 0 0 3px 3px yellow;  
}
.highlight-black {
  -webkit-box-shadow: inset 0 0 3px 3px blue;
  -moz-box-shadow: inset 0 0 3px 3px blue;
  box-shadow: inset 0 0 3px 3px blue;  
}
</style>


<div class="container">
  <br />
  <div class="row">

    <div class ="col-md-8">

      <div id="board" style="width: 500px"></div>

    </div>
    <div class="col-md-2">
      <div class="row">
        <h3><span id="status"></span></h3>
      </div>
      <div class="row">
        <br/>
        <form method="post">{% csrf_token %}
        {{ f.as_p }}
        <input class="btn btn-primary" type="submit" value="Send Trekk" />
        </form>
        <span id="sent"></span>
      </div>
      <div class="row">
        <br />
        <Button class="btn btn-primary" onClick="restoreInitialFen()">Angre</button>
        <br />
      </div>
      <div class="row">
        <br />
        <Button class="btn btn-primary" onClick="resetGame()" >Nytt Spill</button>
        <br />
      </div>
      <div class="row">
        <br />
        <Button class="btn btn-primary" onClick="rotateBoard()">Snu Brettet</button>
        <br />
      </div>
    </div>
    <div class="col-md-2">
      <div class="row">
        <br />
        PGN:
        <br />
        <span id="pgn"></span>
      </div>
    </div>

  </div>

  <div class="row">
    <br />
    <br />
    <p>Funksjoner:</p>
    <ul>
      <li>Send Trekk - Sender trekket ditt til motstanderen.</li>
      <li>Angre - Angre siste trekk, kan bare trykkes dersom man ikke enda har sendt trekket.</li>
      <li>Nytt Spill - Trykk denne etterfulgt av Send Trekk for å starte nytt spill.</li>
      <li>Snu brettet - Snur brettet.</li>
    </ul>
  </div>

</div>


<script src="{% static "js/json3.min.js" %}"></script>
<script src="{% static "js/jquery-1.10.1.min.js" %}"></script>
<script src="{% static "js/chess.min.js" %}"></script>
<script src="{% static "js/chessboard.js" %}"></script>


<script>
var board;
var initialStatus = "Playing";
var initialFen = "{{ gameData.fen }}";
var initialPgn = "{{ gameData.pgn }}"
var pgnE1 = $("#pgn");
var statusE1 = $("#status");
var fen = $("#id_fen")
var game = new Chess();
var moves = 0;


var removeHighlights = function() {
  $("#board").find('.square-55d63')
    .removeClass('highlight-white');
  $("#board").find('.square-55d63')
    .removeClass('highlight-black');
};

var setHighlights = function(source, target, color)
{
  removeHighlights()

  var history = game.history({ verbose:true })
  if (history.length > 0)
  {
    var lastHistoryObject = history[history.length-1]
    var color = 'white'
    if(game.turn() === 'w')
    {
      color = 'black'
    }

    $("#board").find('.square-' + lastHistoryObject.from).addClass('highlight-'+color);
    $("#board").find('.square-' + lastHistoryObject.to).addClass('highlight-'+color);
  }
};

var onDragStart = function(source, piece, position, orientation)
{
  if (game.game_over() == true ||
    (game.turn() === "w" && piece.search(/^b/) !== -1) ||
    (game.turn() === "b" && piece.search(/^w/) !== -1) ||
    moves > 0)
  {
    return false;
  }
}

var onDrop = function(source, target)
{

  var move = game.move({
    from: source,
    to: target,
    promotion: 'q'
  });
  if(move === null) return 'snapback';

  moves += 1;

  canSendMove();
  updateStatus();

}

var updateStatus = function() 
{
  var status = ''

  var moveColor = "Hvit";
  if(game.turn() === 'b'){
    moveColor= "Svart";
  }

  if (game.in_checkmate() === true){
    status = moveColor + " er sjakk matt!"
  }
  else if (game.in_draw() === true)
  {
    status = "Uavgjort!"
  }
  else
  {
    status = moveColor + " sin tur";
    if(game.in_check() === true){
      status += ", sjakk!";
    }
  }

  statusE1.html(status);
  fen.val(game.fen());
  pgnE1.html(game.pgn({ max_width: 5, newline_char: '<br />' }));
};

var onSnapEnd = function(){
  board.position(game.fen());
  updateFen();
};

// Init
// ----------
var init = function() {

var cfg = {
	draggable : true,
  pieceTheme: '{% static "img/chesspieces/wikipedia/" %}{piece}.png',
	position : "{{ gameData.fen }}",
  onSnapEnd: onSnapEnd,
  onDrop: onDrop,
  onDragStart:onDragStart
}
if("{{ gameData.pgn }}" !== "new")
{
  game.load_pgn("{{ gameData.pgn }}")
}
board = new ChessBoard('board', cfg);

$("#id_fen").hide();
$("#id_pgn").hide();
updateFen();

updateStatus();
readCookie();
setHighlights();
}; 
// ---------
// end init()

var rotateBoard = function()
{
  board.flip();
  writeCookie();
};

var updateFen = function()
{
  $("#id_fen").val(game.fen());
  if(game.pgn() == "")
  {
    $("#id_pgn").val("new");
  }
  else
  {
    $("#id_pgn").val(game.pgn());
  }
  setHighlights();
};

var restoreInitialFen = function()
{
  if(initialPgn !== "new")
  {
    game.load_pgn(initialPgn)
    board.position(game.fen());
    updateStatus();
    updateFen();
  }
  else
  {
    game = new Chess();
    board.position(game.fen());
    updateStatus();
    updateFen();
  }
  moves = 0;
  canSendMove();
};

setInterval(function() {
  $.ajax({
    url: 'http://python.torsjakk.com/getGameFen/',
    type: 'get',
    cache: false,
    success: function(data) {
        if(data === initialPgn)
        {
            var doNothing = 0;
        }
        else
        {
          if(data != "new" && data != "")
          {
            game.load_pgn(data)
          }
          else
          {
            game = new Chess();
          }
          initialPgn = game.pgn();
          initialFen = game.fen();
          board.position(game.fen());
          updateStatus();
          updateFen();
          moves = 0;
          canSendMove();
        }
    },
    failure: function(data) {
        alert('Problemer med å laste brettet, er du tilkoblet internett?');
    }
});
}, 5000)

var resetGame = function()
{
  game = new Chess();
  board.position(game.fen());
  updateStatus();
  updateFen();
};

var writeCookie = function()
{
  document.cookie = "name="+board.orientation();
};

var readCookie = function()
{
  var color = getCookie("name");
  if (color === "white")
    board.orientation("white");
  else
    board.orientation("black");
};

function getCookie(cname)
{
var name = cname + "=";
var ca = document.cookie.split(';');
for(var i=0; i<ca.length; i++) 
  {
  var c = ca[i].trim();
  if (c.indexOf(name)==0) return c.substring(name.length,c.length);
  }
return "";
}

var canSendMove = function()
{
  if(moves > 0)
  {
    $("#sent").html("Usendt trekk!")
  }
  else
  {
    $("#sent").html("");
  }
};

$(document).ready(init);
</script>
</body>
</html>